- hosts: client
  vars:
    ansible_user: ubuntu
    inventory: hosts
  tasks:
  - name: Check server connection
    command: echo "Connection is ready"
    tags: ["check-ssh"]
      
  ## Update /etc/hosts
  - name: Add IP hostname pair in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      state: present
      regex: "{{ hostvars[item].ansible_host }} {{ item }}"
      line: "{{ hostvars[item].ansible_host }} {{ item }}"
    with_items: "{{ groups['server'] }}"
  
  ## Install Consul by APT
  ## Consul client would running for Nomad to auto-join cluster
  - name: Add HashiCorp APT key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
  - name: Add HashiCorp APT repository
    apt_repository:
      repo: deb https://apt.releases.hashicorp.com focal main
  - name: Install Nomad package
    package:
      name: consul  
  ## Install Nomad
  - name: Install Nomad package
    package:
      name: nomad  
  
  ## Configure Consul client
  - name: Update Consul config, set retry_join = [ALL_CONSUL_SERVERS]
    lineinfile:
      dest: /etc/consul.d/consul.hcl
      state: present
      regex: "^retry_join = .*"
      line: >-
        retry_join = ["{{ groups['server'] | join('", "')  }}"]
  - name: FIX Consul systemd service file
    # There is a pitfall on Ubuntu 20.04 .deb package
    # https://github.com/hashicorp/consul/issues/11911
    lineinfile:
      dest: /lib/systemd/system/consul.service
      state: present
      regex: "^EnvironmentFile=/etc/consul.d/consul.env"
      line: "EnvironmentFile=-/etc/consul.d/consul.env"
  ## Start Consul services in the cluster
  - name: Start Consul cluster
    systemd:
      name: consul
      state: started
      daemon_reload: yes

  ## Configure Nomad
  ### Must specify cpu_total_compute value because pitfall described below.
  ### [Issue-9511] Fingerprinting fails to detect cpu total compute in arm64
  ### https://github.com/hashicorp/nomad/issues/9511
  - name: Initial Nomad client config
    blockinfile:
      path: /etc/nomad/02-client.hcl 
      create: yes
      block: |
        client {
          enabled = true
          cpu_total_compute = 2000
        }
  ## Start Nomad client
  - name: Start Nomad client
    systemd:
      name: nomad
      state: restarted